In [2]:
import numpy as np

a=np.arange(9)
print(a)

[0 1 2 3 4 5 6 7 8]


In [3]:
b=np.arange(15).reshape(3,5)
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [4]:
a.shape


(9,)

In [5]:
b.shape

(3, 5)

In [6]:
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
a.dtype

dtype('int64')

In [8]:
print(a.size)
print(b.size)
print(type(a))
print(type(b))

9
15
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [9]:
c=np.array([2,3,5,7])
print(c)
c.dtype
c.shape

[2 3 5 7]


(4,)

In [11]:
d=np.array([(1,2,3,4),(5,6,7,8)])
print(d)
print(d.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [12]:
a<5

array([ True,  True,  True,  True,  True, False, False, False, False])

In [13]:
b=np.arange(4)
print(b)
b**2

[0 1 2 3]


array([0, 1, 4, 9])

In [14]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825])

In [15]:
f=np.random.random((2,3))
print(f)
print(f.min())
print(f.max())
print(f.sum())

[[0.05756303 0.63972913 0.25212914]
 [0.73244692 0.64493527 0.47054785]]
0.057563026077072754
0.7324469195851667
2.797351337415625


In [16]:
x=np.fromfunction(lambda i,j:i==j,(4,4),dtype=int)
print(x)

[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]]


In [17]:
##3d array
y=np.array([[[3,4,5],[1,2,3]],[[6,7,8],[9,10,11]]])
print(y)


[[[ 3  4  5]
  [ 1  2  3]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [18]:
y.shape

(2, 2, 3)

In [19]:
y[-1]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [20]:
y[1]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [21]:
y[0]

array([[3, 4, 5],
       [1, 2, 3]])

In [22]:
y[-1][-1]

array([ 9, 10, 11])

In [23]:
####floor

In [24]:
z=np.arange(8)
print(z)
np.hsplit(z,2)

[0 1 2 3 4 5 6 7]


[array([0, 1, 2, 3]), array([4, 5, 6, 7])]